In [1]:
import torch
from torch import nn
import numpy as np

X = torch.tensor([[0., 0],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.]])

y_and = torch.tensor([[0.], [0.], [0.], [1.]])
y_or  = torch.tensor([[0.], [1.], [1.], [1.]])


model = nn.Sequential(
    nn.Linear(2, 1),
    nn.ReLU()
)

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [5]:
for x in model.parameters():
    print(x)

Parameter containing:
tensor([[0.4804, 0.3719]], requires_grad=True)
Parameter containing:
tensor([-0.4597], requires_grad=True)


In [6]:
for epoch in range(1000):
    optimizer.zero_grad()
    
    y_pred = model(X)
    loss = criterion(y_pred, y_and)
    
    loss.backward()
    optimizer.step()

    if epoch % 200 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.0924
Epoch 200, Loss: 0.0012
Epoch 400, Loss: 0.0000
Epoch 600, Loss: 0.0000
Epoch 800, Loss: 0.0000


In [7]:
for x in model.parameters():
    print(x)

Parameter containing:
tensor([[0.9999, 0.9999]], requires_grad=True)
Parameter containing:
tensor([-0.9999], requires_grad=True)


In [142]:
with torch.no_grad():
    print(model(X) > 0.5)

tensor([[False],
        [False],
        [False],
        [ True]])


Epoch 0, Loss: 0.3858
Epoch 200, Loss: 0.0048
Epoch 400, Loss: 0.0002
Epoch 600, Loss: 0.0000
Epoch 800, Loss: 0.0000

Raw network output:
tensor([[0.0000e+00],
        [7.0512e-05],
        [7.0512e-05],
        [9.9990e-01]])

Thresholded output:
tensor([[0.],
        [0.],
        [0.],
        [1.]])


## My implementation

In [24]:
import numpy as np

from module.linear import LinearLayer
from module.relu import ReluLayer
from module.network import NeuralNetwork
from optimizer.sgd import SGD
from criterion.mse import MSELoss


X = np.array([[0., 0],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.]])

y_and = np.array([[0.], [0.], [0.], [1.]])
y_or  = np.array([[0.], [1.], [1.], [1.]])

model = NeuralNetwork([
    LinearLayer(2,1, init="he"),
    ReluLayer()
])

criterion = MSELoss()
optimizer = SGD(model.parameters, lr=1e-3)

In [ ]:
for epoch in range(1000):
    y_pred = model.forward(X)

    loss = criterion.forward(y_and, y_pred)
    
    delta = criterion.backward(y_and, y_pred)
    model.backward(delta)
    
    optimizer.step()

    if epoch % 200 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")



Epoch 0, Loss: 987257196921869734361694208.0000
Epoch 200, Loss: 3524031262979420289715142656.0000
Epoch 400, Loss: 12579089199021695840341196800.0000
Epoch 600, Loss: 44901271659878624422887686144.0000
Epoch 800, Loss: 160275848654528812608351371264.0000
